version: '3.8'

services:
  postgresql:
    build: ./postgresql/
    environment:
      POSTGRES_DB: hypertube
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: kcadmin
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    networks:
      - hypertube_network
    ports:
      - "5432:5432"
volumes:
  postgres_data:

networks:
  hypertube_network:
