FROM quay.io/keycloak/keycloak:26.3.1 AS builder

FROM alpine:latest
RUN apk add --no-cache curl jq openjdk17
COPY --from=builder /opt/keycloak /opt/keycloak
COPY hypertube-realm.json /opt/keycloak/data/import/
COPY entrypoint.sh /opt/keycloak/
RUN chmod +x /opt/keycloak/entrypoint.sh
CMD ["/opt/keycloak/entrypoint.sh"]
