FROM node:20-alpine AS keycloakify-builder
RUN apk add --no-cache maven
WORKDIR /build
COPY ./keycloakify/package*.json ./
RUN npm install -g pnpm
RUN pnpm install
COPY keycloakify/ ./keycloakify/
WORKDIR /build/keycloakify
RUN npm run build-keycloak-theme
FROM quay.io/keycloak/keycloak:26.3.1 AS builder

FROM alpine:latest
RUN apk add --no-cache curl jq openjdk17
COPY --from=builder /opt/keycloak /opt/keycloak
COPY hypertube-realm.json /opt/keycloak/data/import/
COPY entrypoint.sh /opt/keycloak/
# Copy the built theme from the keycloakify build stage
COPY --from=keycloakify-builder /build/keycloakify/dist_keycloak/keycloak-*-versions.jar /opt/keycloak/providers/keycloak-theme.jar
RUN chmod +x /opt/keycloak/entrypoint.sh
RUN /opt/keycloak/bin/kc.sh build
ENTRYPOINT ["/opt/keycloak/entrypoint.sh"]